--- 
- 
  become: true
  become_method: sudo
  hosts: all
  tasks: 
    - 
      name: "stop the container"
      shell: "docker stop jon"
      name: "remove container"
      shell: "docker rm jon"   
      name: "create docker container"
      shell: "docker run -d --name jon -p 1234:8080 ksaaah2008/jon"
